name: Package asset

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - run: echo ${{ steps.package-version.outputs.current-version}}

    - run: |
        mkdir Assets
        mv AdvancedInstanceManager Assets/AdvancedInstanceManager
        mv AdvancedInstanceManager.meta Assets/AdvancedInstanceManager.meta
    
    - run: |
        echo "Assets/AdvancedInstanceManager.meta" > metaList
        find Assets/AdvancedInstanceManager/ -name \*.meta >> metaList
        
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'advanced-instance-manager-${{ steps.package-version.outputs.current-version}}.unitypackage'
        include-files: metaList
        
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBody: true
        prerelease: true
        draft: true
        commit: main
        tag: dev
        artifacts: advanced-instance-manager-${{ steps.package-version.outputs.current-version}}.unitypackage
