name: Create Unity Package

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - run: |
        echo "AdvancedInstanceManager.meta" > metaList
        find AdvancedInstanceManager/ -name \*.meta >> metaList
    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/advanced-instance-manager.unitypackage'
        include-files: metaList
        
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBody: true
        draft: true
        prerelease: true
        commit: main
        artifacts: a/advanced-instance-manager.unitypackage
